xcodeproj 'Tests'
workspace '../CDLJSONPResponseSerializer'
inhibit_all_warnings!

def import_pods
  pod 'AFNetworking', '~> 2.0.3'
  pod 'CDLJSONPResponseSerializer',
      :path => '../CDLJSONPResponseSerializer.podspec'
  pod 'Expecta', '~> 0.2.3'
end

target :ios do
  platform :ios, '7.0'
  link_with 'iOS Tests'
  import_pods
end

target :osx do
  platform :osx, '10.9'
  link_with 'OS X Tests'
  import_pods
end
